### ISSUE TITLE
Available speakers in your region

### ISSUE THREAD

**Issue by gergelyke** [knode/knode.github.io#2]
A calendar would be great, containing speaker candidates (submitted by themselves) and when they travel to foreign countries. This way meetups could easily host the speakers.

**Comment by junosuarez** [comment]
Could you describe more of the workflow you have in mind, to start a discussion? So far, we've avoided a calendar-like approach with the meetups and events themselves, 1) due to maintenance and accuracy, and 2) because it is of more limited use as a global resource. 

Right now we have meetups organized by geographic location. Perhaps we can start another folder with speaker bios, contact info, "home base", topics of interest, past talks + links to online slides/videos, etc - and then speakers can update those as they travel, etc to keep the knode community up to date - and also organizers can reach out to people nearby and potentially invite meetup speakers.

**Comment by hackygolucky** [comment]
I haven't looked to see if http://nodemeatspace.com/ has an API, but it would be nice to have an easily accessible way to see upcoming events in the nodejs/js/web community. I'd prefer to display it on our site in a limited means--such as next 60 days. This would be an added way to see what speakers are ALREADY in-town. This doesn't guarantee they'd be willing to speak as they may not have the bandwidth to do so at that time, but _shrugs_. 

Second the idea of a Speakers repo we can parse and display on the website. !m @jden
