### ISSUE TITLE
KnodeCamp at JSFest--Thursday, March 6th

### ISSUE THREAD

**Issue by hackygolucky** [knode/knode.github.io#20]
As part of JSFest, we've been asked to present KnodeCamp. 

Our initial idea after some discussion:
"A Kuh-node.io Rodeo": KNODE.IO, 'a resource for all things Node.js', is hosting a mini-summit for those interested in growing their node citizenry -- from running a Nodebots day to starting a user group, all the way up to running a conference -- come share war stories, listen, and help contribute to the future of the Node.js community."

Considering format: lightning talk on a small event like a nodebots instance, short talk on a meetup(how are we running them?), long talk on organizing a conference, drinks after for the war stories...and also talking the project origin/roadmap itself? It was requested to make this a bit unconf-y and see how people end up inspired. Do we try to work on the project while we're there?

SCHEDULE: Thursday, March 6th. 10am start, 2 hour break for lunch at noon, done before 6.
LOCATION: Joyent(should also get in touch with Emily at Joyent about this)
CAPACITY: 30 tickets. We should reach out to those we think this is relevant to so we ensure they are definitely there.

cc @rosskukulinski and @nvcexploder 
Let's discuss planning details, implementation, fantastical notions, invites below!

**Comment by hackygolucky** [comment]
tweeted. Thanks for doing the same @rosskukulinski

**Comment by rosskukulinski** [comment]
Sure thing @hackygolucky.  I'll find some time tomorrow to comment here on my thoughts for the event

**Comment by nvcexploder** [comment]
So here are my initial ideas - since there hasn't been a lot of planning on this so far, @hackygolucky and I were considering maybe an unconference? ( Any thoughts/preferences on that @rosskukulinski? ) 

Even without that, there's a few different things that we could prepare:
1. Get some folks to have talks/subjects that they're ready to give a presentation on. Perhaps even reach out to some community people to ask if they'd be willing.
2. Contact @mikeal to see if he has any ideas/recommendations about content. Also ask in regards to tweeting out to attendees about desired content/workshops.
3. Continue compiling info on knode. I'll keep reaching out to folks in other cities to add/update their info on the repo. 
4. Get information about EVERY. TYPE. OF. NODE. MEETING. Different formats of meetups, nodebots, coptors, hacknights, civic hacking, attracting sponsors, getting venues, everything.
5. If we're unconferencing, get unconference supplies - lots of easels, paper, post its, pens, markers, cats, and things to eat/drink.

Right now this is a huge barf of the stuff I've been thinking about - please help me refine && add to.

**Comment by mikeal** [comment]
+1 on unconference.

I'd stay away from prepared talks or material of any kind. If anything people might want to prepare open ended _questions_ that can be discussed. In my experience, the best thing to do is get everyones ideas about what they'd like to discuss first, stick it up on a board and tackle it until lunch, then after lunch get everyone's ideas again because they will have changed and evolved a lot from when everyone first showed up.

The room we've got at Joyent has an entire wall of whiteboard! 

I'm bringing gear to make coffee and we'll have a long break for lunch :) Might want to grab some snacks though.

**Comment by nvcexploder** [comment]
K - sounds good. I would still like to get resources together, not
necessarily to speak on them, but to have them ready quickly for folks.

@mikeal, how many folks have signed up for it?

**Comment by mikeal** [comment]
> I would still like to get resources together, not necessarily to speak on them, but to have them ready quickly for folks.

+1 

> how many folks have signed up for it?

21/30 so it'll likely be close to selling out by the time the event happens.

**Comment by nvcexploder** [comment]
Rad!

**Comment by rosskukulinski** [comment]
and I just bought a ticket for myself.

I agree unconf is smart and no 'talks' is fine.

I feel that there are three major questions/parts people could be interested in:
1) How do I start a group (Venue, guests, food/drink, speakers, hacknights, etc)
2) How do I get involved/help a group
3) How can we (as group leaders) work together on tooling/ideas to make it easier to organize events.  E.g. the nodedc group has got a cool WIP that pulls events from Meetup.com API and displays them on a webpage. Knode also has its own set of tools.

I agree with @mikeal : "If anything people might want to prepare open ended questions that can be discussed"

I'd also like to walk away from the conf with a list of groups/individuals with which we can expand Knode database.  Perhaps leading up to the event we could reach out to the guest list with a _brief_ survey:
1) Do you run a(an) event(s)?
2) What type/types
3) Name of the event
4) Link to event
5) If you don't, are you interested in starting one?
6) What do you hope to take away from this event?

**Comment by hackygolucky** [comment]
Going to try the first take at the schedule. We can let Emily know what to expect at Joyent.

9:00 - 10:00: Setup & Preparation (chairs, whiteboards, breakout room, food & drink)

10:00 - 10:30: Whiteboard Ideas, Snacks, Beverages, Socializing
10:30 - 10:45: Welcome and Introduction to knode.io
10:45 - 11:00: Brainstorm Session Topics (Condense to about 10 topics)
11:00 - 11:15: Post sessions on the grid, allow people to assemble into groups

11:15 - 12:30: Session 1 (5 groups max)
12:30 - 13:00: Report out from Session 1

13:00 - 14:00: Lunch Break

14:00 - 15:15: Session 2 (5 groups max)
15:15 - 15:30: Report out from Session 2

15:30 - 16:30: More funtimes
16:30: Wrap-up, Feedback, Follow-up/follow-through

17:00+: Happy Hour/encourage everyone to go to NodeUp Live for anyone who’s still around

Questions for us and to ask Emily:
what's the setup for people plugging in laptops to display if they have anything they'd like to share while speaking?
Will we have access to whiteboard space? 
What's the space like that we're using? One big room?
Do we want to go the sticky note method re: brainstorming sessions? If so, we need stickies! and markers and pens...

**Comment by hackygolucky** [comment]
BOOM! It's a wrap! :koala: :cake: :icecream:
